apiVersion : apps/v1
kind: Deployment
metadata:
  name: "nextgenaks-518b"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "nextgenaks-518b"
  template:
    metadata:
      labels:
        app: "nextgenaks-518b"
    spec:
      containers:
        - name: "nextgenaks-518b"
          image: "frontiersandbox.azurecr.io/nextgenaks"
          ports:
          - containerPort: 8080